### ISSUE TITLE
Negative integers (larger than -(1 << 5)) do not work  

### ISSUE THREAD

**Issue by hakkabon** [msgpack/msgpack-d#8]
I think that the cause of the problem is to be found in the "Packer pack" function where it tests "if (value < -(1 << 5))" for both int and long integers. Changing the test to " if (value < 0)" seems to fix the problem.

ref Packer pack(T)(in T value) if (isSigned!T && isIntegral!T && !is(Unqual!T == enum)) {
...
  if (value < 0) { 
...

**Comment by RalphBariz** [comment]
After dmd upgrade this fix causes a deprecation.

ralph@ralph ~/Git/My/causal/msgpack-d (git)-[tags/v1.0.0-beta.6] % dmd --version
DMD64 D Compiler v2.078.0
Copyright (c) 1999-2017 by The D Language Foundation written by Walter Bright
ralph@ralph ~/Git/My/causal/msgpack-d (git)-[tags/v1.0.0-beta.6] % dub test
Generating test runner configuration 'msgpack-d-test-library' for 'library' (library).
Excluding package.d file from test due to https://issues.dlang.org/show_bug.cgi?id=11847
Performing "unittest" build using /usr/bin/dmd for x86_64.
msgpack-d ~master: building configuration "msgpack-d-test-library"...
src/msgpack/unpacker.d(199,30): Deprecation: integral promotion not done for -header, use '-transition=intpromote' switch or -cast(int)(header)
src/msgpack/unpacker.d(199,30): Deprecation: integral promotion not done for -header, use '-transition=intpromote' switch or -cast(int)(header)
src/msgpack/unpacker.d(199,21): Deprecation: integral promotion not done for -cast(byte)-header, use '-transition=intpromote' switch or -cast(int)(cast(byte)-header)
src/msgpack/unpacker.d(199,30): Deprecation: integral promotion not done for -header, use '-transition=intpromote' switch or -cast(int)(header)
src/msgpack/unpacker.d(199,21): Deprecation: integral promotion not done for -cast(short)-header, use '-transition=intpromote' switch or -cast(int)(cast(short)-header)
src/msgpack/unpacker.d(199,30): Deprecation: integral promotion not done for -header, use '-transition=intpromote' switch or -cast(int)(header)
Linking...
Running ./msgpack-d-test-library
All unit tests have been run successfully.
